export const API_URL = import.meta.env.VITE_API_URL;

export const colourCode = {
  PENDING: '#FF9D66',
  'CREATION PENDING': '#FF9D66',
  QUEUED: '#FF9D66',
  CREATING: '#FF9D66',
  UPDATING: '#FF9D66',
  DELETING: '#FF9D66',
  'DELETION PENDING': '#FF9D66',
  'IN PROGRESS': '#FF9D66',
  FAILED: '#FF6666',
  'UPDATE FAILED': '#FF6666',
  'CREATION FAILED': '#FF6666',
  'DELETION FAILED': '#FF6666',
  'UPDATE PENDING': '#FF9D66',
  COMPLETED: '#22c55e',
  READY: '#22c55e',
  RUNNING: '#22c55e',
  DELETED: '#FF9D66',
  PICKED: '#FF9D66',
  RUNNABLE: '#FF9D66',
  'EXPORT DONE': '#FF9D66',
  IMPORT: '#FF9D66',
  'IMPORT PENDING': '#FF9D66',
  'IMPORT RUNNING': '#FF9D66',
  EXPORT: '#FF9D66',
  'EXPORT RUNNING': '#FF9D66',
  'EXPORT PENDING': '#FF9D66',
  'IMPORT DONE': '#66FFAC',
  'IMPORT FAILED': '#FF6666',
  'EXPORT FAILED': '#FF6666',
  deployed: '#22c55e',
  uninstalled: '#4b5563',
  superseded: '#FF9D66',
  failed: '#FF6666',
  'pending-install': '#FF9D66',
  'pending-upgrade': '#FF9D66',
  'pending-rollback': '#FF9D66',
  uninstalling: '#FF9D66',
  unknown: '#FF9D66',
  danger: '#FF6666',
  compliant: '#22c55e',
  pending: '#FF9D66',
  unchecked: '#6b7280',
  warning: '#ca8a04',
  PROVISIONING: '#FF9D66',
  STOPPING: '#FF9D66',
};

export const REFRESH_STATUS = [
  'QUEUED',
  'CREATING',
  'DELETING',
  'UPDATING',
  'IN PROGRESS',
  'CREATION PENDING',
  'DELETION PENDING',
  'UPDATE PENDING',
  'PICKED',
  'IMPORT',
  'IMPORT PENDING',
  'IMPORT RUNNING',
  'EXPORT',
  'EXPORT RUNNING',
  'EXPORT PENDING',
  'EXPORT DONE',
  'PENDING',
  'pending',
  'PROVISIONING',
  'STOPPING',
];
