// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -destination=mock_interface.go -package=handler -source=interface.go
//

// Package handler is a generated GoMock package.
package handler

import (
	reflect "reflect"

	models "github.com/zopdev/zopdev/api/resources/providers/models"
	service "github.com/zopdev/zopdev/api/resources/service"
	gomock "go.uber.org/mock/gomock"
	gofr "gofr.dev/pkg/gofr"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ChangeState mocks base method.
func (m *MockService) ChangeState(ctx *gofr.Context, resDetails service.ResourceDetails) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeState", ctx, resDetails)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeState indicates an expected call of ChangeState.
func (mr *MockServiceMockRecorder) ChangeState(ctx, resDetails any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeState", reflect.TypeOf((*MockService)(nil).ChangeState), ctx, resDetails)
}

// GetResources mocks base method.
func (m *MockService) GetResources(ctx *gofr.Context, id int64, resources []string) ([]models.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResources", ctx, id, resources)
	ret0, _ := ret[0].([]models.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResources indicates an expected call of GetResources.
func (mr *MockServiceMockRecorder) GetResources(ctx, id, resources any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResources", reflect.TypeOf((*MockService)(nil).GetResources), ctx, id, resources)
}
