// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -destination=mock_interface.go -package=service -source=interface.go
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gcp "github.com/zopdev/zopdev/api/resources/providers/gcp"
	gomock "go.uber.org/mock/gomock"
	google "golang.org/x/oauth2/google"
	option "google.golang.org/api/option"
)

// MockGCPClient is a mock of GCPClient interface.
type MockGCPClient struct {
	ctrl     *gomock.Controller
	recorder *MockGCPClientMockRecorder
	isgomock struct{}
}

// MockGCPClientMockRecorder is the mock recorder for MockGCPClient.
type MockGCPClientMockRecorder struct {
	mock *MockGCPClient
}

// NewMockGCPClient creates a new mock instance.
func NewMockGCPClient(ctrl *gomock.Controller) *MockGCPClient {
	mock := &MockGCPClient{ctrl: ctrl}
	mock.recorder = &MockGCPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGCPClient) EXPECT() *MockGCPClientMockRecorder {
	return m.recorder
}

// NewGoogleCredentials mocks base method.
func (m *MockGCPClient) NewGoogleCredentials(ctx context.Context, cred any, scopes ...string) (*google.Credentials, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, cred}
	for _, a := range scopes {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewGoogleCredentials", varargs...)
	ret0, _ := ret[0].(*google.Credentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewGoogleCredentials indicates an expected call of NewGoogleCredentials.
func (mr *MockGCPClientMockRecorder) NewGoogleCredentials(ctx, cred any, scopes ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, cred}, scopes...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewGoogleCredentials", reflect.TypeOf((*MockGCPClient)(nil).NewGoogleCredentials), varargs...)
}

// NewSQLInstanceLister mocks base method.
func (m *MockGCPClient) NewSQLInstanceLister(ctx context.Context, opts ...option.ClientOption) (gcp.SQLClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewSQLInstanceLister", varargs...)
	ret0, _ := ret[0].(gcp.SQLClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewSQLInstanceLister indicates an expected call of NewSQLInstanceLister.
func (mr *MockGCPClientMockRecorder) NewSQLInstanceLister(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSQLInstanceLister", reflect.TypeOf((*MockGCPClient)(nil).NewSQLInstanceLister), varargs...)
}
