// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -destination=mock_interface.go -package=handler -source=interface.go
//

// Package handler is a generated GoMock package.
package handler

import (
	reflect "reflect"

	store "github.com/zopdev/zopdev/api/audit/store"
	gomock "go.uber.org/mock/gomock"
	gofr "gofr.dev/pkg/gofr"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetResultByAll mocks base method.
func (m *MockService) GetResultByAll(ctx *gofr.Context, cloudAccId int64) ([]*store.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResultByAll", ctx, cloudAccId)
	ret0, _ := ret[0].([]*store.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResultByAll indicates an expected call of GetResultByAll.
func (mr *MockServiceMockRecorder) GetResultByAll(ctx, cloudAccId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResultByAll", reflect.TypeOf((*MockService)(nil).GetResultByAll), ctx, cloudAccId)
}

// GetResultByCategory mocks base method.
func (m *MockService) GetResultByCategory(ctx *gofr.Context, cloudAccId int64) (map[string][]*store.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResultByCategory", ctx, cloudAccId)
	ret0, _ := ret[0].(map[string][]*store.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResultByCategory indicates an expected call of GetResultByCategory.
func (mr *MockServiceMockRecorder) GetResultByCategory(ctx, cloudAccId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResultByCategory", reflect.TypeOf((*MockService)(nil).GetResultByCategory), ctx, cloudAccId)
}

// GetResultById mocks base method.
func (m *MockService) GetResultById(ctx *gofr.Context, cloudAccId int64, ruleId string) (*store.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResultById", ctx, cloudAccId, ruleId)
	ret0, _ := ret[0].(*store.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResultById indicates an expected call of GetResultById.
func (mr *MockServiceMockRecorder) GetResultById(ctx, cloudAccId, ruleId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResultById", reflect.TypeOf((*MockService)(nil).GetResultById), ctx, cloudAccId, ruleId)
}

// RunAll mocks base method.
func (m *MockService) RunAll(ctx *gofr.Context, cloudAccId int64) (map[string][]*store.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunAll", ctx, cloudAccId)
	ret0, _ := ret[0].(map[string][]*store.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunAll indicates an expected call of RunAll.
func (mr *MockServiceMockRecorder) RunAll(ctx, cloudAccId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunAll", reflect.TypeOf((*MockService)(nil).RunAll), ctx, cloudAccId)
}

// RunByCategory mocks base method.
func (m *MockService) RunByCategory(ctx *gofr.Context, category string, cloudAccId int64) ([]*store.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunByCategory", ctx, category, cloudAccId)
	ret0, _ := ret[0].([]*store.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunByCategory indicates an expected call of RunByCategory.
func (mr *MockServiceMockRecorder) RunByCategory(ctx, category, cloudAccId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunByCategory", reflect.TypeOf((*MockService)(nil).RunByCategory), ctx, category, cloudAccId)
}

// RunById mocks base method.
func (m *MockService) RunById(ctx *gofr.Context, ruleID string, cloudAccId int64) (*store.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunById", ctx, ruleID, cloudAccId)
	ret0, _ := ret[0].(*store.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunById indicates an expected call of RunById.
func (mr *MockServiceMockRecorder) RunById(ctx, ruleID, cloudAccId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunById", reflect.TypeOf((*MockService)(nil).RunById), ctx, ruleID, cloudAccId)
}
